// <auto-generated />
using System;
using ClinicAppointmentAPI.contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClinicAppointmentAPI.Migrations
{
    [DbContext(typeof(ClinicAppointmentContext))]
    partial class ClinicAppointmentContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ClinicAppointmentAPI.Models.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<double>("Exp")
                        .HasColumnType("float");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Qualification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialization")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = 201,
                            DateOfBirth = new DateTime(2002, 3, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Exp = 2.0,
                            Image = "",
                            Name = "Huzair",
                            Qualification = "MBBS",
                            Specialization = "MD"
                        },
                        new
                        {
                            Id = 202,
                            DateOfBirth = new DateTime(2001, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Exp = 3.0,
                            Image = "",
                            Name = "Ahmed",
                            Qualification = "MBBS",
                            Specialization = "ENT"
                        },
                        new
                        {
                            Id = 203,
                            DateOfBirth = new DateTime(2000, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Exp = 4.0,
                            Image = "",
                            Name = "Shree",
                            Qualification = "MBBS",
                            Specialization = "MD"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
